In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
# Test Sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
# Define Vocab size
voc_size=10000

In [12]:
# One hot representation for every word
one_hot_rep=[one_hot(words,voc_size)for words in sent ]
one_hot_rep

[[7743, 3516, 4871, 5613],
 [7743, 3516, 4871, 388],
 [7743, 5649, 4871, 775],
 [52, 7939, 7901, 1990, 9690],
 [52, 7939, 7901, 1990, 1254],
 [6901, 7743, 6985, 4871, 502],
 [8707, 7572, 4821, 1990]]

In [15]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [19]:
# Using pad_sequence to make all sentences of same length
sent_length=8
embedded_docs=pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7743 3516 4871 5613]
 [   0    0    0    0 7743 3516 4871  388]
 [   0    0    0    0 7743 5649 4871  775]
 [   0    0    0   52 7939 7901 1990 9690]
 [   0    0    0   52 7939 7901 1990 1254]
 [   0    0    0 6901 7743 6985 4871  502]
 [   0    0    0    0 8707 7572 4821 1990]]


In [20]:
# Feature Representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 26ms/step


array([[[ 0.0318065 ,  0.01684512, -0.04875542, -0.0171394 ,
          0.0035492 ,  0.00679767,  0.03914714,  0.02623082,
         -0.02302997, -0.04521028],
        [ 0.0318065 ,  0.01684512, -0.04875542, -0.0171394 ,
          0.0035492 ,  0.00679767,  0.03914714,  0.02623082,
         -0.02302997, -0.04521028],
        [ 0.0318065 ,  0.01684512, -0.04875542, -0.0171394 ,
          0.0035492 ,  0.00679767,  0.03914714,  0.02623082,
         -0.02302997, -0.04521028],
        [ 0.0318065 ,  0.01684512, -0.04875542, -0.0171394 ,
          0.0035492 ,  0.00679767,  0.03914714,  0.02623082,
         -0.02302997, -0.04521028],
        [ 0.02229739, -0.00919948, -0.02470627,  0.02358413,
         -0.00893492, -0.01986744,  0.03313366,  0.04789546,
         -0.00740186, -0.04471467],
        [ 0.03746476, -0.0164771 , -0.00917566, -0.0042284 ,
          0.02832044, -0.02570903, -0.02889969,  0.02562897,
          0.00234978, -0.0305512 ],
        [-0.0290313 , -0.02446985,  0.02006784, -0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 7743, 3516, 4871, 5613], dtype=int32)